Fix for result 72
OnFreund/pyrisco pull request #3
Opened 2021-02-08 20:55 UTC by swiergot

This is a fix (or workaround if you will) for the occasional unexpected response with result code 72.

It appears that after getting such response the next request is always successful, so this change should eliminate the issue entirely.

2021-02-09 08:03 UTC, OnFreund requested changes
Looks great other than the name. Maybe also add a code comment for posterity?

2021-02-09 08:03 UTC, OnFreund commented on pyrisco/risco.py
> +                raise MysteriousResultError(str(json))
```suggestion
                raise TemporaryError(str(json))
```

2021-02-09 08:03 UTC, OnFreund commented on pyrisco/risco.py
> +            except MysteriousResultError as e:
```suggestion
            except TemporaryError as e:
```

2021-02-09 08:03 UTC, OnFreund commented on pyrisco/risco.py
> +class MysteriousResultError(Exception):
```suggestion
class TemporaryError(Exception):
```

2021-02-09 10:01 UTC, swiergot commented
Just had a look at the HA logs and found this:

> 2021-02-08 22:01:14 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall alarm_control_panel.alarm_arm_away (c:513884befa7250832e9f45e2a5b1c5e1): entity_id=['alarm_control_panel.risco_dom_partition_2']>
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/core.py", line 1471, in catch_exceptions
> await coro_or_task
> File "/usr/src/homeassistant/homeassistant/core.py", line 1490, in _execute_service
> await handler.job.target(service_call)
> File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
> await self.hass.helpers.service.entity_service_call(
> File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 595, in entity_service_call
> future.result() # pop exception if have
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
> await coro
> File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 632, in _handle_entity_call
> await result
> File "/usr/src/homeassistant/homeassistant/components/risco/alarm_control_panel.py", line 152, in async_alarm_arm_away
> await self._arm(STATE_ALARM_ARMED_AWAY, code)
> File "/usr/src/homeassistant/homeassistant/components/risco/alarm_control_panel.py", line 175, in _arm
> await self._call_alarm_method(risco_state)
> File "/usr/src/homeassistant/homeassistant/components/risco/alarm_control_panel.py", line 178, in _call_alarm_method
> alarm = await getattr(self._risco, method)(self._partition_id, *args)
> File "/usr/local/lib/python3.8/site-packages/pyrisco/risco.py", line 346, in arm
> File "/usr/local/lib/python3.8/site-packages/pyrisco/risco.py", line 266, in _site_post
> "fromControlPanel": True,
> File "/usr/local/lib/python3.8/site-packages/pyrisco/risco.py", line 253, in _authenticated_post
> if json["result"] == 72:
> pyrisco.risco.OperationError: {'result': 72, 'validationErrors': None, 'errorText': None, 'errorTextCodeID': '0', 'status': 200, 'response': {'classVersion': 0, 'partitions': None, 'systemStatus': 2, 'systemReady': False, 'trouble': False, 'bellStatus': 0, 'alarmPending': False, 'batteryLow': False, 'acLost': False, 'haEnabled': False, 'bellOn': False, 'zones': None, 'haDevices': None, 'users': None, 'devCollection': None, 'exitDelayTimeout': 0, 'armNotAllowed': False, 'disarmNotAllowed': False, 'cpTime': '2021-02-08T21:01:14.910696+00:00', 'partReadySupported': False, 'partFullReady': False, 'part1Ready': False, 'part2Ready': False, 'type': 5}}

So for some reason 3 attempts were not enough. Also, this looks different from what we have seen in case of status polling, i.e. response is not null. Anyway, the arm was successful. And this would have been visible before my fix as well, right?

Also, since I applied the fix to HA yesterday at 1:30pm CET, there have been one occurrence of this message:

> 2021-02-09 10:33:34 ERROR (MainThread) [homeassistant.components.risco] Error fetching risco data: {'result': 72, 'validationErrors': None, 'errorText': None, 'errorTextCodeID': None, 'status': 200, 'response': None}

While it's a huge improvement (before the fix I had it like a dozen times a day), I hoped it would eliminate the problem completely. Now it appears that either 3 attempts are not enough or we need some delay before a retry (1-2 seconds).

I will add the delay on my HA to see if it helps.

2021-02-10 08:45 UTC, OnFreund commented
Given what you've found I'm starting to think we should let the error bubble up (as it was) and have the caller (the HA integration) handle the retry and delay. I could see pros and cons either way, but unlike the session expiring every hour, which is expected and thus makes sense foe the library to handle, this is more voodoo.

Did you manage to test with delay?

2021-02-10 09:06 UTC, swiergot commented
Still testing. Apparently I wasted some time yesterday believing that the integration was reloaded with new changes but for some reason it wasn't, so eventually I had to restart HA. I have also added some debugging messages. All I have seen so far are relogins due to expired sessions, not a single response 72.

2021-02-10 09:51 UTC, swiergot commented
Speaking of the devil...

2021-02-10 10:36:19 WARNING (MainThread) [homeassistant.components.risco] RISCO: got 72, raising TemporaryError
2021-02-10 10:36:19 WARNING (MainThread) [homeassistant.components.risco] RISCO: catched TemporaryError in iteration 0
2021-02-10 10:36:19 WARNING (MainThread) [homeassistant.components.risco] RISCO: Sleeping before the next attempt
2021-02-10 10:36:22 WARNING (MainThread) [homeassistant.components.risco] RISCO: Done sleeping
2021-02-10 10:36:40 WARNING (MainThread) [homeassistant.components.risco] RISCO: got 72, raising TemporaryError
2021-02-10 10:36:40 WARNING (MainThread) [homeassistant.components.risco] RISCO: catched TemporaryError in iteration 1
2021-02-10 10:36:40 WARNING (MainThread) [homeassistant.components.risco] RISCO: Sleeping before the next attempt
2021-02-10 10:36:43 WARNING (MainThread) [homeassistant.components.risco] RISCO: Done sleeping

It worked in the third attempt. Will keep testing.

2021-02-10 13:09 UTC, swiergot commented
Another occurrence and it's quite interesting. The weird state lasted for over 1 minute this time. It appears that requests finishing with result 72 take significantly longer to complete than successful requests. On my HA a successful request takes 2-4 seconds. In the below messages we have four unsuccessful requests that can be measured based on log timestamps and every single one of them took ~17 seconds.

2021-02-10 13:14:21 WARNING (MainThread) [homeassistant.components.risco] RISCO: got 72, raising TemporaryError
2021-02-10 13:14:21 WARNING (MainThread) [homeassistant.components.risco] RISCO: catched TemporaryError in iteration 0
2021-02-10 13:14:21 WARNING (MainThread) [homeassistant.components.risco] RISCO: Sleeping before the next attempt
**2021-02-10 13:14:24 WARNING (MainThread) [homeassistant.components.risco] RISCO: Done sleeping
2021-02-10 13:14:41 WARNING (MainThread) [homeassistant.components.risco] RISCO: got 72, raising TemporaryError**
2021-02-10 13:14:41 WARNING (MainThread) [homeassistant.components.risco] RISCO: catched TemporaryError in iteration 1
2021-02-10 13:14:41 WARNING (MainThread) [homeassistant.components.risco] RISCO: Sleeping before the next attempt
**2021-02-10 13:14:44 WARNING (MainThread) [homeassistant.components.risco] RISCO: Done sleeping
2021-02-10 13:15:01 WARNING (MainThread) [homeassistant.components.risco] RISCO: got 72, raising TemporaryError**
2021-02-10 13:15:01 WARNING (MainThread) [homeassistant.components.risco] RISCO: catched TemporaryError in iteration 2
2021-02-10 13:15:01 WARNING (MainThread) [homeassistant.components.risco] RISCO: iterations limit reached, raising OperationError
**2021-02-10 13:15:01 ERROR (MainThread) [homeassistant.components.risco] Error fetching risco data: {'result': 72, 'validationErrors': None, 'errorText': None, 'errorTextCodeID': None, 'status': 200, 'response': None}
_+ 3 seconds polling interval_
2021-02-10 13:15:22 WARNING (MainThread) [homeassistant.components.risco] RISCO: got 72, raising TemporaryError**
2021-02-10 13:15:22 WARNING (MainThread) [homeassistant.components.risco] RISCO: catched TemporaryError in iteration 0
2021-02-10 13:15:22 WARNING (MainThread) [homeassistant.components.risco] RISCO: Sleeping before the next attempt
**2021-02-10 13:15:25 WARNING (MainThread) [homeassistant.components.risco] RISCO: Done sleeping
2021-02-10 13:15:42 WARNING (MainThread) [homeassistant.components.risco] RISCO: got 72, raising TemporaryError**
2021-02-10 13:15:42 WARNING (MainThread) [homeassistant.components.risco] RISCO: catched TemporaryError in iteration 1
2021-02-10 13:15:42 WARNING (MainThread) [homeassistant.components.risco] RISCO: Sleeping before the next attempt
2021-02-10 13:15:45 WARNING (MainThread) [homeassistant.components.risco] RISCO: Done sleeping

So I have extended logging to capture: a) execution time of unsuccessful requests and b) successful requests that take more than 5 seconds. And I got this:

2021-02-10 13:54:48 WARNING (MainThread) [homeassistant.components.risco] RISCO: got 72, raising TemporaryError, request **took 16.3**
2021-02-10 13:54:48 WARNING (MainThread) [homeassistant.components.risco] RISCO: catched TemporaryError in iteration 0
2021-02-10 13:54:48 WARNING (MainThread) [homeassistant.components.risco] RISCO: Sleeping before the next attempt
2021-02-10 13:54:51 WARNING (MainThread) [homeassistant.components.risco] RISCO: Done sleeping
2021-02-10 13:55:08 WARNING (MainThread) [homeassistant.components.risco] RISCO: got 72, raising TemporaryError, request **took 17.2**
2021-02-10 13:55:08 WARNING (MainThread) [homeassistant.components.risco] RISCO: catched TemporaryError in iteration 1
2021-02-10 13:55:08 WARNING (MainThread) [homeassistant.components.risco] RISCO: Sleeping before the next attempt
2021-02-10 13:55:11 WARNING (MainThread) [homeassistant.components.risco] RISCO: Done sleeping
2021-02-10 13:55:25 WARNING (MainThread) [homeassistant.components.risco] RISCO: successful request **took 14.1**
2021-02-10 13:55:45 WARNING (MainThread) [homeassistant.components.risco] RISCO: got 72, raising TemporaryError, request **took 17.3**
2021-02-10 13:55:45 WARNING (MainThread) [homeassistant.components.risco] RISCO: catched TemporaryError in iteration 0
2021-02-10 13:55:45 WARNING (MainThread) [homeassistant.components.risco] RISCO: Sleeping before the next attempt
2021-02-10 13:55:48 WARNING (MainThread) [homeassistant.components.risco] RISCO: Done sleeping

This makes me think that perhaps this result code means something like "I'm too busy right now to serve your request, come back later" and there is a 15-16 seconds timeout in place.

2021-02-10 13:46 UTC, swiergot commented
Another possibility is that each time we make the request, the cloud goes to the panel and the panel does not respond in a timely manner (but otherwise sends keepalives in expected intervals). My panel has a GSM/GPRS module so I cannot verify this, but if you have an ethernet module and a router that allows sniffing, you could easily see if there is traffic every time the request is made.

One more thing, I can see that the web client polls for GetCPState, while the library uses GetState. I know GetCPState doesn't always return full status, but probably only when something changes. Is there any other reason for using GetState?

2021-02-10 16:01 UTC, OnFreund commented
> One more thing, I can see that the web client polls for GetCPState, while the library uses GetState. I know GetCPState doesn't always return full status, but probably only when something changes. Is there any other reason for using GetState?

The integration is based on the mobile api, not the web API. I don't know what is the different between `GetCPState` and `GetState`.


Your GSM/GPRS connection can definitely explain why this happens more often for you than it does for me (my system is connected via ethernet). You might be right - this is a result of the panel being unavailable.
Given that though, I'm not sure the current behavior is a bug. What we can do, is within the HA options flow, decide what period of unavailability we're willing to accept before marking the entity unavailable.
As for this PR, I'm not sure that's the right approach anymore given your findings.

2021-02-12 08:45 UTC, swiergot commented
Yesterday I did an experiment. I powered off my panel and guess what, the cloud started returning result 72. To make things even more complicated, this night the cloud was returning result 17 for 6 minutes...

All in all, I agree with you. I will open another pull request, this time for the integration.

2021-02-12 08:45 UTC, closed without merging